export const productArrayNewGames = [
  {
    name: "Robot War ",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/robotwar.jpg",
    id: "N-1",
    label: "new",
    price: 299,
  },
  {
    name: "Let Her In",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus esse nobis in minus.",
    image: "gamecovers/letherin.jpg",
    id: "N-2",
    label: "new",
    price: 299,
  },
  {
    name: "Skull Part II",
    description: "Quia, placeat!",
    image: "gamecovers/skullpartII.jpg",
    id: "N-3",
    label: "new",
    price: 399,
  },
  {
    name: "Bone Cracker",
    description: "Quia, placeat!",
    image: "gamecovers/bonecracker.jpg",
    id: "N-4",
    label: "new",
    price: 299,
  },
  {
    name: "Donkey Kong",
    description: "Quia, placeat!",
    image: "gamecovers/donkeykong.jpg",
    id: "N-5",
    label: "new",
    price: 399,
  },
];

export const productArrayUsedGames = [
  {
    name: "OverWatch",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/overwatch.jpg",
    id: "U-1",
    label: "used",
    price: 199,
  },
  {
    name: "Blue Dragon",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus esse nobis in minus.",
    image: "gamecovers/bluedragon.jpg",
    id: "U-2",
    label: "used",
    price: 150,
  },
  {
    name: "Come See Him",
    description: "Quia, placeat!",
    image: "gamecovers/comeseehim.jpg",
    id: "U-3",
    label: "used",
    price: 150,
  },
  {
    name: "Green Soldier",
    description: "Quia, placeat!",
    image: "gamecovers/greensoldier.jpg",
    id: "U-4",
    label: "used",
    price: 200,
  },
  {
    name: "Ancient Fighter",
    description: "Quia, placeat!",
    image: "gamecovers/ancientfighter.jpg",
    id: "U-5",
    label: "used",
    price: 150,
  },
];
