export const productArrayNewGames = [
  {
    name: "Robot War ",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/robotwar.jpg",
    id: "1",
    label: "new",
    price: 299,
  },
  {
    name: "Let Her In",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus esse nobis in minus.",
    image: "gamecovers/letherin.jpg",
    id: "2",
    label: "new",
    price: 299,
  },
  {
    name: "Skull Part II",
    description: "Quia, placeat!",
    image: "gamecovers/skullpartII.jpg",
    id: "3",
    label: "new",
    price: 399,
  },
  {
    name: "Bone Cracker",
    description: "Quia, placeat!",
    image: "gamecovers/bonecracker.jpg",
    id: "4",
    label: "new",
    price: 299,
  },
  {
    name: "Donkey Kong",
    description: "Quia, placeat!",
    image: "gamecovers/donkeykong.jpg",
    id: "5",
    label: "new",
    price: 399,
  },
  {
    name: "Robot War ",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/robotwar.jpg",
    id: "6",
    label: "new",
    price: 299,
  },
  {
    name: "Let Her In",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus.",
    image: "gamecovers/letherin.jpg",
    id: "7",
    label: "new",
    price: 299,
  },
  {
    name: "Skull Part II",
    description: "Quia, placeat!",
    image: "gamecovers/skullpartII.jpg",
    id: "8",
    label: "new",
    price: 399,
  },
  {
    name: "Bone Cracker",
    description: "Quia, placeat!",
    image: "gamecovers/bonecracker.jpg",
    id: "9",
    label: "new",
    price: 299,
  },
  {
    name: "Donkey Kong",
    description: "Quia, placeat!",
    image: "gamecovers/donkeykong.jpg",
    id: "10",
    label: "new",
    price: 399,
  },
];

export const productArrayUsedGames = [
  {
    name: "OverWatch",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/overwatch.jpg",
    id: "1",
    label: "used",
    price: 199,
  },
  {
    name: "Blue Dragon",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus esse nobis in minus.",
    image: "gamecovers/bluedragon.jpg",
    id: "2",
    label: "used",
    price: 150,
  },
  {
    name: "Come See Him",
    description: "Quia, placeat!",
    image: "gamecovers/comeseehim.jpg",
    id: "3",
    label: "used",
    price: 150,
  },
  {
    name: "Green Soldier",
    description: "Quia, placeat!",
    image: "gamecovers/greensoldier.jpg",
    id: "4",
    label: "used",
    price: 200,
  },
  {
    name: "Ancient Fighter",
    description: "Quia, placeat!",
    image: "gamecovers/ancientfighter.jpg",
    id: "5",
    label: "used",
    price: 150,
  },
  {
    name: "OverWatch",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/overwatch.jpg",
    id: "6",
    label: "used",
    price: 199,
  },
  {
    name: "Blue Dragon",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus esse nobis in minus.",
    image: "gamecovers/bluedragon.jpg",
    id: "7",
    label: "used",
    price: 150,
  },
  {
    name: "Come See Him",
    description: "Quia, placeat!",
    image: "gamecovers/comeseehim.jpg",
    id: "8",
    label: "used",
    price: 150,
  },
];

export const productArraySimilarGames = [
  {
    name: "Long Horn",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    image: "gamecovers/longhorn.jpg",
    id: "1",
    newlabel: "",
    usedlabel: "used",
    price: 199,
  },
  {
    name: "Her Skull",
    description: "Aliquam eos natus sint nihil aut aliquid hic necessitatibus esse nobis in minus.",
    image: "gamecovers/herskull.jpg",
    id: "2",
    newlabel: "new",
    usedlabel: "",
    price: 399,
  },
  {
    name: "Lord of the Skulls",
    description: "Quia, placeat!",
    image: "gamecovers/lordoftheskulls.jpg",
    id: "3",
    newlabel: "",
    usedlabel: "used",
    price: 150,
  },
  {
    name: "Let Her In",
    description: "Quia, placeat!",
    image: "gamecovers/letherin.jpg",
    id: "4",
    newlabel: "new",
    usedlabel: "",
    price: 299,
  },
  {
    name: "Bone Cracker",
    description: "Quia, placeat!",
    image: "gamecovers/bonecracker.jpg",
    id: "5",
    newlabel: "new",
    usedlabel: "",
    price: 299,
  },
];
